### ISSUE TITLE
Problem with backgrond-position in IE 11

### ISSUE THREAD

**Issue by holyzfy** [sirxemic/jquery.ripples#21]
## Steps to reproduce

edit index.html in source file

```css
main {
    background: url(img/bg.jpg) no-repeat center center; /* that's fine */
}
```

It doen't work when change `background-position` to `center top`:
```css
main {
    background: url(img/bg.jpg) no-repeat center top;
}
```
